import { Toaster } from "sonner";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Toaster position="top-center" richColors />
      <body className=" font-['Helvetica-Bold',Helvetica]">{children}</body>
    </html>
  );
}
